name: Monthly accessibility scans

on:
  push:
  schedule:
    - cron: '0 0 1 * *' 

jobs:
  wellington-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 800

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Playwright
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install trafilatura playwright tqdm axe-core-python
        playwright install
        playwright install-deps

    - name: Generate URLs for wellington.govt.nz
      run: trafilatura --sitemap -u https://wellington.govt.nz/sitemap.xml --list > urls.txt

    - name: Run wellington.govt.nz axe scan
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 420
        max_attempts: 2
        command: python wcc-axe.py

    - name: Commit changes
      run: |
        git pull
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add *
        git commit -m "New a11y report for wellington.govt.nz" || echo "No changes to commit"
        git push

  letstalk-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 800

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Playwright
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install trafilatura playwright tqdm axe-core-python
        playwright install
        playwright install-deps

    - name: Generate URLs for letstalk.wellington.govt.nz
      run: trafilatura --sitemap -u https://www.letstalk.wellington.govt.nz/sitemap.xml --list > letstalkurls.txt

    - name: Run letstalk.wellington.govt.nz scan
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 420
        max_attempts: 2
        command: python letstalk-axe.py

    - name: Commit letstalk.wellington.govt.nz changes
      run: |
        git pull
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add *
        git commit -m "New a11y report for letstalk.wellington.govt.nz" || echo "No changes to commit"
        git push

  create-release:
    needs: [wellington-scan, letstalk-scan]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate tag version
      id: tag_version
      run: echo "new_tag=$(date +'v%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create a new release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Monthly accessibility reports
        body: New a11y reports for wellington.govt.nz and letstalk.wellington.govt.nz
        artifacts: "*.csv"
        allowUpdates: true
