name: Monthly TEPP accessibility scan

on:
  schedule:
    - cron: '0 0 1 * *'  

jobs:
  run-accessibility-test:
    runs-on: ubuntu-latest
    timeout-minutes: 800

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Run Playwright test
      run: npm run test:accessibility

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add *
        git commit -m "New a11y report for outdoor event bookings" || echo "No changes to commit"
        git push

    - name: Generate tag version
      id: tag_version
      run: echo "new_tag=$(date +'v%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create a new release
      if: success() # Only create a release if the previous steps were successful
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Monthly accessibility report for outdoor event booking
        body: New a11y report for services.wellington.govt.nz/outdoor-event-booking
        artifacts: "*.csv"
        allowUpdates: true
